# Generated by Django 3.0.6 on 2020-05-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200524_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='posts.Comment'),
        ),
    ]
