# Generated by Django 3.0.6 on 2020-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200524_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='upcomment',
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
