version: '3.8'

services:
    web:
        build: .
        command: gunicorn blog_api.wsgi -b 0.0.0.0:8000
        env_file:
            - .env
#        volumes:
#            - ./django_blog_api:/blog
        ports:
            - "8000:8000"

